name: 'Run LLM finetuning template tests'
inputs:
  ref-zenml:
    description: 'Ref of ZenML package'
    type: string
    required: false
    default: ''
  ref-template:
    description: 'Ref of this template repo'
    type: string
    required: false
    default: ''
  python-version:
    description: 'Python version'
    type: string
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        repository: zenml-io/template-llm-finetuning
        ref: ${{ inputs.ref-template }}
        path: ./local_checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Configure git (non-Windows)
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        git config --global user.email "info@zenml.io"
        git config --global user.name "ZenML GmbH"
    
    - name: Configure git (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        "C:\Program Files\Git\bin\git.exe" config --global user.email "info@zenml.io"
        "C:\Program Files\Git\bin\git.exe" config --global user.name "ZenML GmbH"

    - name: Install wheel
      shell: bash
      run: |
        pip install wheel uv
    
    - name: Install ZenML
      if: ${{ inputs.ref-zenml != '' }}
      shell: bash
      env:
        UV_HTTP_TIMEOUT: '1000'
      run: |
        uv pip install --system "zenml[dev, templates]@git+https://github.com/zenml-io/zenml.git@${{ inputs.ref-zenml }}"
    
    - name: Install ZenML
      if: ${{ inputs.ref-zenml == '' }}
      shell: bash
      env:
        UV_HTTP_TIMEOUT: '1000'
      run: |
        uv pip install --system "zenml[dev, templates]"

    - name: Install requirements
      shell: bash
      env:
        UV_HTTP_TIMEOUT: '1000'
      run: |
        uv pip install --system -r ./local_checkout/test-requirements.txt
        uv pip install --system -r ./local_checkout/template/requirements.txt
        uv pip install --system "pyyaml-include<2.0"

    - name: Run pytests
      shell: bash
      run: |
        pytest -s ./local_checkout/tests

    - name: Clean-up
      shell: bash
      run: |
        rm -rf ./local_checkout
