model:
  name: {{ product_name }}-{{ model_repository.split("/") | last }}
  description: "Fine-tune `{{ model_repository }}`."
  tags:
    - llm
    - lora
    - {{ model_repository }}

settings:
  docker:
    parent_image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

steps:
  evaluate:
    enable_step_logs: False
    parameters:
      config:
        {%- if huggingface_merged_model_repository %}
        model_repo: {{ huggingface_merged_model_repository }}
        {%- else %}
        model_repo: {{ model_repository }}
        from_safetensors: {{ from_safetensors }}
        adapter_repo: {{ huggingface_adapter_model_repository }}
        {%- endif %}
        precision: bf16-true