model:
  name: {{ product_name }}-{{ model_repository.split("/") | last }}
  description: "Fine-tune `{{ model_repository }}`."
  tags:
    - llm
    - lora
    - {{ model_repository }}

steps:
  feature_engineering:
    enable_step_logs: False
    parameters:
      config:
        model_repo: {{ model_repository }}
        dataset_name: csv
        prepare_kwargs:
          # REQUIRED: Path the the .csv file containing the data. Format must be as described here
          # https://github.com/Lightning-AI/litgpt/blob/main/tutorials/prepare_dataset.md#preparing-custom-datasets-from-a-csv-file
          csv_path: null
