model:
  name: {{ product_name }}-{{ model_repository.split("/") | last }}
  description: "Fine-tune `{{ model_repository }}`."
  tags:
    - llm
    - lora
    - {{ model_repository }}
    - alpaca

steps:
  feature_engineering:
    enable_step_logs: False
    parameters:
      config:
        model_repo: {{ model_repository }}
        dataset_name: alpaca
